<div class="jumbotron jumbotron-fluid jumbotron-image">
  <div class="container">
    <h1 class="display-4 text-center font-weight-bold font-color-white">Hello Developer!</h1>
    <p class="lead text-center mt-1 font-color-white">Lorem ipsum dolor, sit amet consectetur adipisicing elit</p>
  </div>
</div>
<div class="container d-flex justify-content-center flex-wrap">
  <div class="card">
    <img class="card-img-top" src="<?php echo $this->getViewFileUrl('David_CustomModule::images/400x300.png'); ?>" alt="Card image cap">
    <div class="card-body">
      <!-- <h5 class="card-title">Card title</h5> -->
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <div class="d-flex justify-content-center">
        <a href="#" class="btn btn-outline-dark">READ MORE</a>
      </div>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="<?php echo $this->getViewFileUrl('David_CustomModule::images/400x300.png'); ?>" alt="Card image cap">
    <div class="card-body">
      <!-- <h5 class="card-title">Card title</h5> -->
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <div class="d-flex justify-content-center">
        <a href="#" class="btn btn-outline-dark">READ MORE</a>
      </div>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="<?php echo $this->getViewFileUrl('David_CustomModule::images/400x300.png'); ?>" alt="Card image cap">
    <div class="card-body">
      <!-- <h5 class="card-title">Card title</h5> -->
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <div class="d-flex justify-content-center">
        <a href="#" class="btn btn-outline-dark">READ MORE</a>
      </div>
    </div>
  </div>
</div>